### ISSUE TITLE
Visited link color

### ISSUE THREAD

**Issue by JasonBarnabe** [necolas/css3-social-signin-buttons#9]
My default a:visited rules are taking effect on the buttons and it makes them look bad. Here's the code I had to add:

``` css
a.btn-auth:visited {
    color: #222;
}
a.btn-facebook:visited, a.btn-google:visited {
    color: white;
}
a.btn-twitter:visited {
    color: #327695;
}
```
